DATASET:
    NAME: "transparent11_boundary"
    MEAN: [0.485, 0.456, 0.406]
    STD: [0.229, 0.224, 0.225]
TRAIN:
    EPOCHS: 80
    BATCH_SIZE: 2
    CROP_SIZE: 513
    MODEL_SAVE_DIR: 'workdirs/transparent_new/translab_r50_80'
TEST:
    BATCH_SIZE: 4
    CROP_SIZE: (513, 513)

SOLVER:
    LR: 0.01

MODEL:
    MODEL_NAME: "TransLab"
    BACKBONE: "resnet50"