DATASET:
    NAME: "transparent11"
    MEAN: [0.485, 0.456, 0.406]
    STD: [0.229, 0.224, 0.225]
TRAIN:
    EPOCHS: 150
    BATCH_SIZE: 4
    CROP_SIZE: 513
    MODEL_SAVE_DIR: 'workdirs/transparent_new/pspnet_r50_150'
TEST:
    BATCH_SIZE: 4
    CROP_SIZE: (513, 513)

SOLVER:
    LR: 0.01
    AUX: True
    AUX_WEIGHT: 0.4

AUG:
    BLUR_PROB: 0.5

MODEL:
    MODEL_NAME: "PSPNet"
    BACKBONE: "resnet101c"
    OUTPUT_STRIDE: 8
