DATASET:
    NAME: "transparent11"
    MEAN: [0.485, 0.456, 0.406]
    STD: [0.229, 0.224, 0.225]
TRAIN:
    EPOCHS: 50
    BATCH_SIZE: 4
    CROP_SIZE: 480
    BASE_SIZE: 513
    MODEL_SAVE_DIR: 'workdirs/trans10kv2/danet'
TEST:
    BATCH_SIZE: 4
    CROP_SIZE: (513, 513)

SOLVER:
    LR: 0.003

MODEL:
    MODEL_NAME: "DANet"
    BACKBONE: "resnet50"
    OUTPUT_STRIDE: 8
    DANET:
        MULTI_GRID: True
        MULTI_DILATION: [4, 8, 16]
