DATASET:
    NAME: "transparent11"
    MEAN: [0.5, 0.5, 0.5]
    STD: [0.5, 0.5, 0.5]
TRAIN:
    EPOCHS: 50
    BATCH_SIZE: 4
    CROP_SIZE: 480
    BASE_SIZE: 513
    MODEL_SAVE_DIR: 'workdirs/trans10kv2/deeplab_xp65'
TEST:
    BATCH_SIZE: 4
    CROP_SIZE: (513, 513)

SOLVER:
    LR: 0.01

MODEL:
    MODEL_NAME: "DeepLabV3_Plus"
    BACKBONE: "xception65"
    BN_EPS_FOR_ENCODER: 1e-3
