DATASET:
    NAME: "transparent11"
    MEAN: [0.485, 0.456, 0.406]
    STD: [0.229, 0.224, 0.225]
TRAIN:
    EPOCHS: 100
    BATCH_SIZE: 4
    CROP_SIZE: 480
    BASE_SIZE: 513
    MODEL_SAVE_DIR: 'workdirs/trans10kv2/espnetv2'
TEST:
    BATCH_SIZE: 4
    CROP_SIZE: (512, 512)

SOLVER:
    LR: 0.001

MODEL:
    MODEL_NAME: "ESPNetV2"
    BACKBONE: "eespnet"

