DATASET:
    NAME: "transparent11"
    MEAN: [0.485, 0.456, 0.406]
    STD: [0.229, 0.224, 0.225]
TRAIN:
    EPOCHS: 100
    BATCH_SIZE: 4
    CROP_SIZE: 480
    BASE_SIZE: 513
    MODEL_SAVE_DIR: 'workdirs/trans10kv2/fast_scnn'
TEST:
    BATCH_SIZE: 4
    CROP_SIZE: (512, 512)

SOLVER:
    LR: 0.045
    DECODER_LR_FACTOR: 1.0
    WEIGHT_DECAY: 4e-5
    AUX: True
    AUX_WEIGHT: 0.4

AUG:
    COLOR_JITTER: 0.4

MODEL:
    MODEL_NAME: "FastSCNN"
    BN_MOMENTUM: 0.01
