DATASET:
    NAME: "transparent11"
    MEAN: [0.485, 0.456, 0.406]
    STD: [0.229, 0.224, 0.225]
TRAIN:
    EPOCHS: 50
    BATCH_SIZE: 4
    CROP_SIZE: 480
    BASE_SIZE: 513
    MODEL_SAVE_DIR: 'workdirs/trans10kv2/pspnet'
TEST:
    BATCH_SIZE: 4
    CROP_SIZE: (513, 513)

SOLVER:
    LR: 0.01
    AUX: True
    AUX_WEIGHT: 0.4

AUG:
    BLUR_PROB: 0.5

MODEL:
    MODEL_NAME: "PSPNet"
    BACKBONE: "resnet50"
    OUTPUT_STRIDE: 8
