DATASET:
    NAME: "transparent11_boundary"
    MEAN: [0.485, 0.456, 0.406]
    STD: [0.229, 0.224, 0.225]
TRAIN:
    EPOCHS: 50
    BATCH_SIZE: 4
    CROP_SIZE: 480
    BASE_SIZE: 513
    MODEL_SAVE_DIR: 'workdirs/trans10kv2/translab_r50_v1'
TEST:
    BATCH_SIZE: 32
    CROP_SIZE: (513, 513)

SOLVER:
    LR: 0.01

MODEL:
    MODEL_NAME: "TransLab"
    BACKBONE: "resnet50"
    TRANSLAB:
        BOUNDARY_WEIGHT: 5
